import { test } from 'node:test';
import assert from 'node:assert/strict';
import { columnHeading, isFooterTotalOrNote, isSectionLabel, nonPersonReason } from './personKey.js';

test('nonPersonReason: titles, headings, totals, footers, captions and counts are never people', () => {
  for (const label of ['Waiter 3', 'Head waiter 1', 'RM', 'JAM', 'Supervisor', 'Ops Manager', 'Events Manager', 'Runner 2nd', 'NAME', 'TITLE', 'Staff', 'Day of the week', 'Total staff on rota', 'Total staff on rota: 22', 'Headcount', 'Number of staff', 'Prepared by: Duty Manager', 'Printed 2026-08-17', 'Page 1 of 2', 'Signature ________', 'COVERS', 'Notes', '22']) {
    assert.ok(nonPersonReason(label), label);
  }
  for (const name of ['Test Alpha', 'Saffiya Okonkwo', 'KIKI', 'Jojo', "Rodel D'Cruz", 'Ana-Maria Popescu', 'Nguyễn Thị Lan']) {
    assert.equal(nonPersonReason(name), null, name);
  }
  assert.match(nonPersonReason('Waiter 3')!, /title/);
  assert.match(nonPersonReason('Total staff on rota')!, /total/);
});

test('isFooterTotalOrNote and columnHeading', () => {
  assert.equal(isFooterTotalOrNote('Total staff on rota 20'), true);
  assert.equal(isFooterTotalOrNote('Test Alpha'), false);
  assert.equal(columnHeading('NAME'), 'name');
  assert.equal(columnHeading('Employee name'), 'name');
  assert.equal(columnHeading('TITLE'), 'title');
  assert.equal(columnHeading('Position'), 'title');
  assert.equal(columnHeading('DATE'), null);
});

test('nonPersonReason: heading lines in any order, footers anywhere in the line, department banners and role abbreviations are never people', () => {
  for (const label of ['NAME TITLE', 'STAFF NAME POSITION', '# EMPLOYEE', 'Position S/N Staff', 'No. Name Role', 'Name / Position']) {
    assert.match(nonPersonReason(label)!, /heading/, label);
  }
  for (const label of ['Rota issued 10/04/2026 by Operations', 'Generated by RotaPlanner 3.2 - confidential', 'Updated 12 Apr 2026', 'Version 4']) {
    assert.match(nonPersonReason(label)!, /footer or note/, label);
  }
  for (const label of ['BAR', 'HOSTS', 'MANAGEMENT', 'Kitchen team', 'FOH', 'Senior Servers', 'RUNNERS']) {
    assert.ok(nonPersonReason(label), label);
    assert.equal(isSectionLabel(label), true, label);
  }
  for (const label of ['AGM', 'HOD', 'CDP', 'Senior Server', 'Jr Bartender']) assert.match(nonPersonReason(label)!, /title or role/, label);
  for (const name of ['James Barr', 'Barbara Floor', 'James', 'Test Cooks', 'T. Valdez', 'Valdez T.', 'A. Obi']) assert.equal(nonPersonReason(name), null, name);
});

test('columnHeading: index, name, title and other columns', () => {
  for (const label of ['#', 'No.', 'S/N', 'Sr. No', 'S.No', 'Emp ID', 'Staff No', 'Employee No.']) assert.equal(columnHeading(label), 'index', label);
  for (const label of ['STAFF NAME', 'Employee', 'Surname', 'Employee Full Name', 'Name of employee', 'First Name', 'Team Member']) assert.equal(columnHeading(label), 'name', label);
  for (const label of ['POSITION', 'Role', 'Job title', 'Role / Position', 'Designation']) assert.equal(columnHeading(label), 'title', label);
  for (const label of ['DATE', 'Day of the week', 'Team', 'Ana Silva', 'Name / Position']) assert.equal(columnHeading(label), null, label);
  for (const label of ['TOTAL', 'Signature', 'Dept']) assert.equal(columnHeading(label), 'other', label);
});
