import { isRoleTitle, nameKey } from './resolveRows.js';

/**
 * Groups every shift of one person within one file: the normalized name plus the page and row
 * the person was first read on, so two different people sharing a name stay apart.
 */
export function personKeyOf(name: string, page: number | null, row: number | null): string {
  return `${nameKey(name)}@${page ?? 0}:${row ?? 0}`;
}

/**
 * True when a label reads like a person's name: one to five words of letters (any script),
 * apostrophes, hyphens or dots — no digits, no colon, not overly long.
 */
export function looksLikePersonName(label: string): boolean {
  const s = label.trim();
  if (s.length < 2 || s.length > 40 || /[\d:@#=]/.test(s)) return false;
  const words = s.split(/\s+/);
  return words.length <= 5 && words.every((w) => /^[\p{L}][\p{L}'’.\-]*$/u.test(w));
}

/** Column and row headings ("NAME", "TITLE", "Staff", "Day of the week"). */
const HEADER_WORD = /^(names?|full names?|staff( names?| members?)?|employees?( names?)?|team( members?)?|title|job title|roles?|positions?|designations?|grades?|dept|department|date|dates|days?|day of the week|events?|shifts?)$/i;
/** Totals and counts ("Total staff on rota", "Headcount", "Number of staff"). */
const SUMMARY_LINE = /^(totals?|sub ?totals?|grand totals?|sum|count|head ?count|number of|no\.? of|hours)\b/i;
/** Footers, signatures and notes ("Prepared by", "Printed on", "Page 1 of 2", "Notes"). */
const NOTE_LINE = /^(prepared|approved|printed|signed|signature|checked|authori[sz]ed|legend|key|page|notes?|remarks?|comments?)\b/i;
/** Captions that describe the day, not a person (a covers count, events). */
const CAPTION_LINE = /^(covers?|pax|events?|functions?|bookings?|reservations?|forecast|occupancy)\b/i;

/** A total or count line, a footer, signature or note ("Total staff on rota", "Prepared by: …", "Page 1 of 2"). */
export function isFooterTotalOrNote(label: string): boolean {
  const s = label.trim().replace(/\s+/g, ' ');
  return SUMMARY_LINE.test(s) || NOTE_LINE.test(s) || /\bpage \d+ of \d+\b/i.test(s) || /:\s*\S/.test(s) || /_{3,}/.test(s);
}

/** Words a footer or a printed-by line carries anywhere ("Rota issued 10/04 by Operations", "Generated by … confidential"). */
const FOOTER_WORD = /\b(issued|generated|created|printed|updated|revised|confidential|version|prepared|approved|signature|copyright)\b|©/i;
/** A date or a version number inside a line ("10/04/2026", "v3.2"): a person's name never carries one. */
const DATE_OR_VERSION = /\b\d{1,2}[/.-]\d{1,2}([/.-]\d{2,4})?\b|\b(19|20)\d{2}\b|\bv?\d+\.\d+\b/i;

const INDEX_MARK = new Set(['#', 'no', 'no.', 'nos', 'nos.', 'num', 'number', 's/n', 'sn', 's.no', 's.no.', 'sno', 'sr', 'sr.', 'sl', 'sl.', 'id', 'ref', 'ref.', 'code']);
const INDEX_OWNER = new Set(['emp', 'emp.', 'employee', 'staff', 'serial']);
const NAME_CORE = new Set(['name', 'names', 'surname', 'surnames', 'staff', 'employee', 'employees', 'member', 'members', 'associate', 'associates', 'colleague', 'colleagues']);
const NAME_WORD = new Set([...NAME_CORE, 'full', 'first', 'last', 'given', 'family', 'emp', 'emp.', 'team', 'of', 'the', 'and']);
const TITLE_CORE = new Set(['title', 'titles', 'job', 'role', 'roles', 'position', 'positions', 'designation', 'designations', 'grade', 'grades', 'rank']);
const TITLE_WORD = new Set([...TITLE_CORE, 'of', 'the', 'and']);
const OTHER_WORD = new Set(['total', 'totals', 'hours', 'hrs', 'signature', 'signatures', 'sign', 'note', 'notes', 'remark', 'remarks', 'comment', 'comments', 'dept', 'dept.', 'department', 'departments', 'section', 'sections', 'contract', 'ot']);

/**
 * A column heading: over the names ("NAME", "Staff", "Employee full name"), over the titles
 * ("TITLE", "Job title", "Role / Position"), over an index or number column ("#", "No.", "S/N",
 * "Emp ID"), or over another column that is neither ("TOTAL", "Signature", "Dept"). Read word by
 * word, so any wording made of those words counts.
 */
export function columnHeading(label: string): 'name' | 'title' | 'index' | 'other' | null {
  const tokens = label
    .trim()
    .toLowerCase()
    .replace(/\s+\/\s+/g, ' ')
    .split(/[\s,&+|]+/)
    .flatMap((t) => (t === 's/n' ? [t] : t.split('/')))
    .map((t) => t.replace(/:$/, ''))
    .filter(Boolean);
  if (tokens.length === 0) return null;
  const all = (set: Set<string>) => tokens.every((t) => set.has(t));
  const some = (set: Set<string>) => tokens.some((t) => set.has(t));
  if (tokens.every((t) => INDEX_MARK.has(t) || INDEX_OWNER.has(t)) && some(INDEX_MARK)) return 'index';
  if (all(NAME_WORD) && some(NAME_CORE)) return 'name';
  if (all(TITLE_WORD) && some(TITLE_CORE)) return 'title';
  if (all(OTHER_WORD)) return 'other';
  return null;
}

/** One word of a heading line ("STAFF NAME", "# EMPLOYEE", "Name / Position", "No. Name Title"). */
const HEADING_TOKEN = /^(#|no\.?|s\/n|sn|sr\.?|sl\.?|id|ref|names?|full|first|last|surnames?|staff|employees?|emp\.?|team|members?|titles?|job|roles?|positions?|designations?|grades?|dept\.?|departments?|sections?|totals?|hours|hrs|signatures?|date|dates|days?|of|the|week|shifts?|notes?|remarks?)$/i;
/** A heading line: two or more words, every one of them a heading word. */
function isHeadingLine(s: string): boolean {
  const tokens = s.replace(/\s+\/\s+/g, ' ').split(/[\s|,&+]+/).filter(Boolean);
  const heading = (t: string) => HEADING_TOKEN.test(t) || (t.includes('/') && t.split('/').every((p) => p.length > 1 && HEADING_TOKEN.test(p)));
  return tokens.length >= 2 && tokens.every(heading);
}

/** Department, area and section words ("BAR", "HOSTS", "MANAGEMENT", "TERRACE", "Front of house", "Kitchen team"). */
const SECTION_WORD = /^(bar|bars|floor|service|kitchen|pastry|reception|door|valet|security|stewarding|housekeeping|cleaning|cashiers?|management|admin(istration)?|operations|front of house|back of house|foh|boh|f ?& ?b|hosts|hostesses|runners|bussers|servers|waiters|waitresses|bartenders|barbacks|baristas|sommeliers|chefs|cooks|supervisors|managers|captains|trainees|interns|casuals|relief|terrace|lounge|pool|beach|rooftop|garden|patio|main dining|private dining|banquets?|outlet)( (team|staff|crew|section|department|dept))?$/i;

/**
 * A department or section banner rather than a person: a department word ("BAR", "Kitchen
 * team", "FOH") or a role in the plural ("HOSTS", "Senior Servers").
 */
export function isSectionLabel(label: string): boolean {
  const s = label.trim().replace(/\s+/g, ' ');
  if (!s) return false;
  if (SECTION_WORD.test(s)) return true;
  // A group named as such ("FLOOR AND BAR SERVICE TEAM", "Night crew").
  if (/\s(team|staff|crew|squad|section|department|dept|group)$/i.test(s)) return true;
  // "HOSTS" -> "Host"; a short word is left alone ("James" is not "JAM" in the plural).
  const singular = s.replace(/(?<=\p{L}{4})s$/iu, '');
  return singular !== s && isRoleTitle(singular);
}

/**
 * Why a row label is not a person, or null when it may be one. Every reader asks this before
 * listing someone: a role or title ("Waiter 3", "RM", "Ops Manager"), a column or section
 * heading ("NAME TITLE", "BAR"), a total or count line, a footer, signature or note, a
 * caption, or a bare number is never imported as a person.
 */
export function nonPersonReason(label: string): string | null {
  const s = label.trim().replace(/\s+/g, ' ');
  if (!s) return 'blank';
  if (/^\d+([.,]\d+)?$/.test(s)) return 'a count, not a name';
  if (HEADER_WORD.test(s) || isHeadingLine(s) || columnHeading(s)) return 'a heading, not a name';
  if (SUMMARY_LINE.test(s)) return 'a total or count line, not a person';
  if (NOTE_LINE.test(s) || /\bpage \d+ of \d+\b/i.test(s) || /:\s*\S/.test(s) || /_{3,}/.test(s)) return 'a footer or note, not a person';
  if (FOOTER_WORD.test(s) || DATE_OR_VERSION.test(s)) return 'a footer or note, not a person';
  if (CAPTION_LINE.test(s)) return 'a caption, not a person';
  if (isSectionLabel(s)) return 'a section heading, not a name';
  if (isRoleTitle(s)) return 'a title or role, not a name';
  return null;
}
